# Generated by Django 4.2.1 on 2023-05-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=4000)),
                ('preco_ingresso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresso_meia', models.BooleanField()),
                ('ingresso_comunitario', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('uso', models.CharField(choices=[('EN', 'Ensaio'), ('MNT', 'Montagem do Palco'), ('AP', 'Apresentação'), ('DMNT', 'Desmontagem do Palco')], default='AP', max_length=5)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.event')),
            ],
        ),
    ]
