# Generated by Django 4.2.1 on 2023-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gratuito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingresso_comunitario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingresso_meia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='preco_ingresso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
