# Generated by Django 4.0.4 on 2023-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_eventimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
